

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children, user,messages,analytics}) {
  return (
<>
<div>

{children}

</div>
<div style={{display:"flex", gap:"20px"}}>
<div style={{display:"flex",flexDirection:"column",gap:"20px"}}>
<div style={{height:"100px", border:"1px solid", width:"200px", display:"flex", justifyContent:"center",alignItems:"center"}}>
  {user}
</div>
<div style={{height:"100px", border:"1px solid", width:"200px", display:"flex", justifyContent:"center",alignItems:"center"}}>
  {analytics}
</div>
</div>
<div style={{height:"220px", border:"1px solid", width:"250px", display:"flex", justifyContent:"center",alignItems:"center"}}>
  {messages}
</div>
</div>



</>
      

  
  
  );
}
